{
 "title": "Tinderbox",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "user"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total{mode=\"nice\"}[$__rate_interval]))",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "running images",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tinderbox_images_running", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "emerges / hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tinderbox_emerge_completed_img[1h])) * 3600",
     "legendFormat": "pkgs"
    }
   ]
  },
  {
   "title": "emerges / hr / image",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(img) (rate(tinderbox_emerge_completed_img[1h])) * 3600",
     "legendFormat": "{{img}}"
    }
   ]
  }
 ]
}