{
 "title": "Tinderbox",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Job", "label": "Job", "query": { "query": "label_values(node_os_info,job)" } },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_os_info{job=~\"$Job\"},instance)"
    }
   },
   {
    "name": "Img",
    "label": "Img",
    "query": {
     "query": "label_values(tinderbox_age_img_total,img)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Emerge per Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tinderbox_emerge_completed_img_total{job=~\"$Job\", instance=~\"$Instance\", img=~\"$Img\"}[1h])) * 86400",
     "legendFormat": "1 h"
    },
    {
     "expr": "sum(rate(tinderbox_emerge_completed_img_total{instance=~\"$Instance\", job=~\"$Job\"}[24h])) * 86400",
     "legendFormat": "1 d"
    },
    {
     "expr": "sum(rate(tinderbox_emerge_completed_img_total{instance=~\"$Instance\", job=~\"$Job\"}[144h])) * 86400",
     "legendFormat": "1 w"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"user\", instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "user"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"system\", instance=~\"$Instance\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=\"nice\", instance=~\"$Instance\"}[$__rate_interval])) * 100) / on(label) sum(rate(node_cpu_seconds_total{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "Active Images",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "tinderbox_images{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance=~\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance=~\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Emerges / Img / Hr",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(img) (rate(tinderbox_emerge_completed_img_total{job=~\"$Job\", instance=~\"$Instance\", img=~\"$Img\"}[4h])) * 3600",
     "legendFormat": "{{img}}"
    }
   ]
  },
  {
   "title": "Steve",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "steve{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Age in days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort(tinderbox_age_img_total{job=~\"$Job\", instance=~\"$Instance\", img=~\"$Img\"}) / 86400",
     "legendFormat": "{{img}}"
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by(cpu) (node_cpu_scaling_frequency_hertz{instance=~\"$Instance\", job=~\"$Job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data raid1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(block_group_type, block_group_type, uuid) (node_btrfs_used_bytes{mode=\"raid1\", instance=~\"$Instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(block_group_type, uuid) (node_btrfs_size_bytes{mode=\"raid1\", instance=~\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data raid0",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_btrfs_used_bytes{mode=\"raid0\", instance=~\"$Instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_btrfs_size_bytes{mode=\"raid0\", instance=~\"$Instance\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"nvme0n1|nvme1n1\", instance=~\"$Instance\", job=~\"$Job\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"nvme0n1|nvme1n1\", instance=~\"$Instance\"}[24h]))",
     "legendFormat": "1 d"
    }
   ]
  }
 ]
}